# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17gaWlhG1HzNc3enAQxMGU57i_2SkLPVy
"""



print(Classification_report(y_test_bal,y_pred))
train_score=accuracy_score(y_bal,rfrl1.predict(x_bal))
train_score
1.0

y_pred=xgb.pred(x_test_bal)
print(classification_report(y_test_bal,y_pred))

y_pred=model.predicit(x_test_bal)

random_svc=RandomizedSearchCV(sv,param,scoring-'accuracy',cv-5,n_jobs=1
random_svc.fit(x_bal,y_bal))

random_svc.best_paras_
sv1=SVC(kernel='rbf',gamma=0.1,c=100
sv1.fit(x_bal,y_bal))
y_pred=sv1.predtict(x_test_bal)

print(classification_report(y_test_bal,y_pred))
train_score=accuracy_score(y_bal,sv1.predict(x_bal))
train_score

import pickle
pickle.dump(sv1,open('thyroid_1_model.pkl','wb'))
features=np.array([[0,0,0,0.00000,0.0,0.1.00,0.0,40.0]])
print(label_encoder.inverse_transform(xgb1.predtict(features)))

pickle.dump(lable_encoder,open('label_encoder.pk1','wb'))
data['target'].unique()
y['target'].unique()
array([5,4,1,6,2,3,0])

